package com.efei.lib.android.persistence.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ACCOUNT.
 */
public class Account {

    private String email_mobile;
    private String password;
    private String authKey;
    private java.util.Date lastLoginDate;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Account() {
    }

    public Account(String email_mobile, String password, String authKey, java.util.Date lastLoginDate) {
        this.email_mobile = email_mobile;
        this.password = password;
        this.authKey = authKey;
        this.lastLoginDate = lastLoginDate;
    }

    public String getEmail_mobile() {
        return email_mobile;
    }

    public void setEmail_mobile(String email_mobile) {
        this.email_mobile = email_mobile;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getAuthKey() {
        return authKey;
    }

    public void setAuthKey(String authKey) {
        this.authKey = authKey;
    }

    public java.util.Date getLastLoginDate() {
        return lastLoginDate;
    }

    public void setLastLoginDate(java.util.Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
