package com.efei.lib.android.persistence.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table TEACHER.
 */
public class Teacher {

    private Long id;
    private String teacherId;
    private String name;
    private String subject;
    private String school;
    private String desc;
    private String avatar;
    private long userId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Teacher() {
    }

    public Teacher(Long id) {
        this.id = id;
    }

    public Teacher(Long id, String teacherId, String name, String subject, String school, String desc, String avatar, long userId) {
        this.id = id;
        this.teacherId = teacherId;
        this.name = name;
        this.subject = subject;
        this.school = school;
        this.desc = desc;
        this.avatar = avatar;
        this.userId = userId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTeacherId() {
        return teacherId;
    }

    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getSchool() {
        return school;
    }

    public void setSchool(String school) {
        this.school = school;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
